// Rules-based emergency triage used when the AI Gateway is unreachable
// (offline, rate-limited, or timeout). Deterministic, on-device, no network.
// Not a substitute for the AI assessment - the UI clearly labels it as a
// fallback so the patient can still act while connectivity is restored.

import type { AiAssessment } from "./emergency.functions";

type FallbackInput = {
  symptoms: string[];
  symptomsText?: string;
  painLevel?: number;
  age?: number;
  medicalHistory?: string;
  language?: "en" | "sn" | "nd";
};

const CRITICAL_TAGS = new Set([
  "Unconscious",
  "Stroke signs",
  "Severe bleeding",
  "Seizure",
  "Allergic reaction",
  "Difficulty breathing",
  "Poisoning",
]);
const HIGH_TAGS = new Set([
  "Chest pain",
  "Shortness of breath",
  "Head injury",
  "Severe burn",
  "Broken bone",
  "Pregnancy",
  "High fever",
]);

const CRITICAL_RE =
  /(unconscious|not breathing|no pulse|stroke|seizure|convuls|bleeding heavily|anaphylax|choking|drown|cardiac|heart attack)/i;
const HIGH_RE = /(chest pain|shortness of breath|severe|broken|fracture|burn|head injury|pregnan|overdose|poison)/i;

export function ruleBasedTriage(input: FallbackInput): AiAssessment {
  const text = `${input.symptomsText ?? ""} ${input.medicalHistory ?? ""}`;
  const pain = input.painLevel ?? 0;
  const hasCriticalTag = input.symptoms.some((s) => CRITICAL_TAGS.has(s));
  const hasHighTag = input.symptoms.some((s) => HIGH_TAGS.has(s));

  let severity: AiAssessment["severity"] = "low";
  if (hasCriticalTag || CRITICAL_RE.test(text) || pain >= 9) severity = "critical";
  else if (hasHighTag || HIGH_RE.test(text) || pain >= 7) severity = "high";
  else if (pain >= 4) severity = "medium";

  const primary = input.symptoms[0] ?? "General emergency";
  const specialty =
    /chest|heart|cardiac/i.test(primary + text)
      ? "Cardiology"
      : /stroke|seizure|head|unconscious/i.test(primary + text)
        ? "Neurology / Emergency"
        : /burn/i.test(primary + text)
          ? "Burn unit / Emergency"
          : /pregnan/i.test(primary + text)
            ? "Obstetrics"
            : /breathing|shortness/i.test(primary + text)
              ? "Pulmonology / Emergency"
              : "Emergency medicine";

  const firstAid: string[] = [];
  if (severity === "critical" || severity === "high") {
    firstAid.push("Call 999 or 112 immediately if you have not already.");
    firstAid.push("Keep the patient still. Do not give food or water.");
  }
  if (/bleed/i.test(text) || input.symptoms.includes("Severe bleeding")) {
    firstAid.push("Apply firm, direct pressure to the wound with a clean cloth.");
  }
  if (input.symptoms.includes("Unconscious")) {
    firstAid.push("Check breathing. If trained, place them in the recovery position.");
  }
  if (input.symptoms.includes("Burn") || /burn/i.test(text)) {
    firstAid.push("Cool the burn under running water for 20 minutes. Do not apply creams.");
  }
  if (firstAid.length === 0) {
    firstAid.push("Stay calm and keep the patient comfortable while help is arranged.");
  }

  const redFlags = [
    "Loss of consciousness",
    "Difficulty breathing that worsens",
    "Uncontrolled bleeding",
    "Sudden confusion or facial droop",
  ];

  const headline =
    severity === "critical"
      ? "Critical: seek immediate care"
      : severity === "high"
        ? "High priority: urgent evaluation needed"
        : severity === "medium"
          ? "Moderate: prompt medical review"
          : "Low urgency: monitor and seek care if worse";

  const summary = `Offline triage generated on-device from reported symptoms (${input.symptoms.join(", ") || "free text"}) and pain level ${pain}/10. AI Gateway was unreachable - reassess with the AI once connectivity returns.`;

  const hospitalReport = `[OFFLINE TRIAGE - RULE-BASED FALLBACK]
Severity: ${severity.toUpperCase()}
Age: ${input.age ?? "unknown"}
Pain: ${pain}/10
Symptom tags: ${input.symptoms.join(", ") || "none"}
Patient description: ${input.symptomsText || "none"}
Medical history: ${input.medicalHistory || "none"}
Recommended specialty: ${specialty}
Note: This report was generated by the LifeLine+ on-device fallback (no AI). Clinical staff should re-triage on arrival.`;

  return {
    severity,
    headline,
    summary,
    recommendedSpecialty: specialty,
    firstAid,
    redFlags,
    hospitalReport,
  };
}